= Jakarta WebSocket
:toc: auto

== Introduction
Jakarta WebSocket defines a set of Java APIs for the development of WebSocket applications.

== Building from Source

This repository contains the source for:

* The https://jakarta.ee/specifications/websocket/2.0/apidocs[Jakarta WebSocket API] (`/api`)
* The https://jakarta.ee/specifications/websocket/2.0/websocket-spec-2.0.html[Jakarta WebSocket specification] (`/spec`)

=== API

Jakarta WebSocket API can be built by executing the following from the project root:

[source,bash]
----
cd api
mvn clean package
----
The API jars can then be found in `/api/client/target` and `/api/server/target`.

=== Specification

Jakarta WebSocket specification can be built by executing the following from the project root:

[source,bash]
----
cd spec
mvn clean package
----
The zip archive containing the specification in PDF and HTML format can then be found in `/spec/target`.

== TCK Challenges

All test challenges for Jakarta WebSocket must be resolved by Active Resolution.
Please see the TCK Users guide for more details.

== Making Changes

To make changes, fork this repository, make your changes, and submit a pull request.
